wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683099897.152507
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.9.16
      5: 0.15.1
      8:
      - 5
goal:
  desc: null
  value: cnn
device:
  desc: null
  value: cuda
device_id:
  desc: null
  value: '7'
dataset:
  desc: null
  value: Cifar10
num_classes:
  desc: null
  value: 10
model:
  desc: null
  value: cnn
head:
  desc: null
  value: cnn
batch_size:
  desc: null
  value: 10
local_learning_rate:
  desc: null
  value: 0.005
global_rounds:
  desc: null
  value: 3
local_steps:
  desc: null
  value: 1
algorithm:
  desc: null
  value: FedCentral
join_ratio:
  desc: null
  value: 1.0
random_join_ratio:
  desc: null
  value: false
num_clients:
  desc: null
  value: 10
prev:
  desc: null
  value: 0
times:
  desc: null
  value: 1
eval_gap:
  desc: null
  value: 1
privacy:
  desc: null
  value: false
dp_sigma:
  desc: null
  value: 0.0
save_folder_name:
  desc: null
  value: items
client_drop_rate:
  desc: null
  value: 0.0
train_slow_rate:
  desc: null
  value: 0.0
send_slow_rate:
  desc: null
  value: 0.0
time_select:
  desc: null
  value: false
time_threthold:
  desc: null
  value: 10000
beta:
  desc: null
  value: 0.5
lamda:
  desc: null
  value: 1.0
mu:
  desc: null
  value: 0
K:
  desc: null
  value: 5
p_learning_rate:
  desc: null
  value: 0.01
M:
  desc: null
  value: 5
itk:
  desc: null
  value: 4000
alphaK:
  desc: null
  value: 1.0
sigma:
  desc: null
  value: 1.0
alpha:
  desc: null
  value: 1.0
plocal_steps:
  desc: null
  value: 1
tau:
  desc: null
  value: 1.0
fine_tuning_steps:
  desc: null
  value: 1
dr_learning_rate:
  desc: null
  value: 0.0
L:
  desc: null
  value: 1.0
finetune_round:
  desc: null
  value: 0
static_weight:
  desc: null
  value: 0.0
rho:
  desc: null
  value: 1.0
epsilon:
  desc: null
  value: 1.0
test_id:
  desc: null
  value: 90002
data_dir:
  desc: null
  value: null
central_data_num:
  desc: null
  value: 1
central_data_dir:
  desc: null
  value: Cifar10_central
